# Generated by Django 5.0.6 on 2024-05-28 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('tags', models.CharField(max_length=1024)),
                ('topic', models.CharField(max_length=256)),
                ('language', models.CharField(max_length=32)),
                ('duration', models.IntegerField()),
                ('difficulty', models.DecimalField(decimal_places=1, max_digits=2)),
                ('detail', models.DecimalField(decimal_places=1, max_digits=2)),
                ('userscore', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Trajectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('tags', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='TrajElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('tags', models.CharField(max_length=1024)),
                ('courses', models.ManyToManyField(to='roadmaps.course')),
                ('trajectory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmaps.trajectory')),
            ],
        ),
    ]
