# Generated by Django 5.0.6 on 2024-06-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0003_remove_profile_id_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed_elements',
            field=models.ManyToManyField(to='roadmaps.trajelement'),
        ),
    ]
