# Generated by Django 5.0.6 on 2024-06-18 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0004_profile_completed_elements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('curators', models.ManyToManyField(related_name='curator_set', to='roadmaps.profile')),
                ('participants', models.ManyToManyField(related_name='participant_set', to='roadmaps.profile')),
                ('trajectory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmaps.trajectory')),
            ],
        ),
    ]
