# Generated by Django 5.0.6 on 2024-06-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0005_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='curators',
            field=models.ManyToManyField(related_name='curated_groups', to='roadmaps.profile'),
        ),
        migrations.AlterField(
            model_name='group',
            name='participants',
            field=models.ManyToManyField(related_name='part_of_groups', to='roadmaps.profile'),
        ),
    ]
